[Service]
Host = "localhost"
Port = 5555
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

[StaticProxy]
CoreDataHost     = "localhost"
CoreDataPort     = "48080"
CoreMetadataHost = "localhost"
CoreMetadataPort = "48081"
CoreCommandHost  = "localhost"
CoreCommandPort  = "48082"
CoreExportHost   = "localhost"
CoreExportPort   = "48071"
RuleEngineHost   = "localhost"
RuleEnginePort   = "48075"
SupportLoggingHost   = "localhost"
SupportLoggingPort   = "48061"
SupportNotificationHost   = "localhost"
SupportNotificationPort   = "48060"
SupportSchedulerHost   = "localhost"
SupportSchedulerPort   = "48085"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="1.0"
