[Service]
Host = "localhost"
Port = 5555
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

[StaticProxy]
SystemAgentHost     = "localhost"
SystemAgentPort     = "48090"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="1.0"
