[Service]
Host = "edgex-ui-go"
Port = 5555
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

[StaticProxy]
SystemAgentName     = "edgex-sys-mgmt-agent"
SystemAgentHost     = "edgex-sys-mgmt-agent"
SystemAgentPort     = "48090"

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="1.0"
